// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQmZPXqZQEizamXRY79VLab5p-No6nDI',
    appId: '1:658117655877:web:48295ddeca1f451d1e922c',
    messagingSenderId: '658117655877',
    projectId: 'inappmessaging-87820',
    authDomain: 'inappmessaging-87820.firebaseapp.com',
    storageBucket: 'inappmessaging-87820.firebasestorage.app',
    measurementId: 'G-KM16RZGNN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEf9LtR7eFHo5U0Uuqj_c69DnUVvhZe7w',
    appId: '1:658117655877:android:63a3ddd3f10ba8961e922c',
    messagingSenderId: '658117655877',
    projectId: 'inappmessaging-87820',
    storageBucket: 'inappmessaging-87820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMdDFlOX2gUNiWrRZhuPfUJpBfyJVoXts',
    appId: '1:658117655877:ios:15d954cf175a1b411e922c',
    messagingSenderId: '658117655877',
    projectId: 'inappmessaging-87820',
    storageBucket: 'inappmessaging-87820.firebasestorage.app',
    iosBundleId: 'com.example.testingInAppMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMdDFlOX2gUNiWrRZhuPfUJpBfyJVoXts',
    appId: '1:658117655877:ios:15d954cf175a1b411e922c',
    messagingSenderId: '658117655877',
    projectId: 'inappmessaging-87820',
    storageBucket: 'inappmessaging-87820.firebasestorage.app',
    iosBundleId: 'com.example.testingInAppMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASQmZPXqZQEizamXRY79VLab5p-No6nDI',
    appId: '1:658117655877:web:9b6d14809f4f3b5b1e922c',
    messagingSenderId: '658117655877',
    projectId: 'inappmessaging-87820',
    authDomain: 'inappmessaging-87820.firebaseapp.com',
    storageBucket: 'inappmessaging-87820.firebasestorage.app',
    measurementId: 'G-N014XL4K3D',
  );

}